version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: service1
    IMAGE_TAG: latest
    AWS_DEFAULT_REGION: us-east-1
    ACCOUNT_ID: 412128478995
    EC2_HOST: 3.92.134.179
    HOST_PORT: 8081
    TEMP_PORT: 9090

phases:
  pre_build:
    commands:
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - mkdir -p ~/.ssh
      - aws ssm get-parameter --name "codebuild-ssh-key" --with-decryption --region $AWS_DEFAULT_REGION --query "Parameter.Value" --output text | base64 -d > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keygen -y -f ~/.ssh/id_rsa > /dev/null && echo "Key is valid"
      - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      - echo "Deploying to EC2..."
      - |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@$EC2_HOST bash -s << 'ENDSSH'
          set -e

          IMAGE=412128478995.dkr.ecr.us-east-1.amazonaws.com/service1:latest

          echo "Logging into ECR on EC2..."
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 412128478995.dkr.ecr.us-east-1.amazonaws.com

          echo "Pull latest image"
          docker pull $IMAGE

          echo "Start NEW container on TEMP port"
          docker run -d -p 9090:8080 --name service1-new $IMAGE

          echo "Waiting for app readiness..."
          for i in {1..20}; do
            if curl -s http://localhost:9090 > /dev/null; then
              echo "New container is ready"
              break
            fi
            sleep 3
          done

          echo "Stopping OLD container"
          docker stop service1-container || true
          docker rm service1-container || true

          echo "Starting NEW container on LIVE port"
          docker run -d -p 8081:8080 --name service1-container $IMAGE

          echo "Cleaning TEMP container"
          docker stop service1-new || true
          docker rm service1-new || true

          echo "Deployment complete!"
        ENDSSH